version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - "80:10010"
    links:
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27027:27027"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db
    command: "/true"
