swagger: "2.0"
info:
  version: "0.0.1"
  title: schibsted test
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
schemes:
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/plain

paths:
  /config/{client}/{version}:
    x-swagger-router-controller: config
    get:
      operationId: read
      description: Get all changed configurations since the last received change for a given client and version
      parameters:
        - name: client
          in: path
          type: string
          required: true
          description: Identifier for the client (e.g. "ios-m-omni")
        - name: version
          in: path
          type: string
          required: true
          description: Build version of the client (e.g. "267")
        - name: If-None-Match
          in: header
          type: string
          required: false
          description: The ETag of the last acquired configuration (e.g. W/"1")
      responses:
        304:
          description: No changed fields
        200:
          description: An object with changes since the given ETag
          schema:
            example: '{ "ads_endpoint": "/devads" }'
        default:
          description: Error
  /config:
    x-swagger-router-controller: config
    post:
      operationId: upsert
      description: Change or create a configuration
      parameters:
        - name: body
          in: body
          required: true
          schema:
            required:
              - client
              - version
              - key
              - value
            properties:
              client:
                type: string
              version:
                type: string
              key:
                type: string
              value:
                type: string
      responses:
        201:
          description: Created
        default:
          description: Error

  /swagger:
    x-swagger-pipe: swagger_raw
